### ISSUE TITLE
Templates CRUD

### ISSUE THREAD

**Issue by luizalbsilva** [ourcities/hub-api#49]
Create, remove and list templates, classified by mine or global ones

**Comment by gabrielrtakeda** [comment]
Hi @luizalbsilva! It needs to keep the `goal` field in **template_mobilizations** table to save the template description. One more thing that needs to do is, accepts **name** and **goal** values from post request payload.

The template create form is following below:
<img width="600" alt="screen shot 2016-10-28 at 12 50 36" src="https://cloud.githubusercontent.com/assets/5435389/19811796/b10d4b28-9d11-11e6-958a-b67c4e1f8019.png">

It is a good choice to keep the `goal` field because, when creates a mobilization by a template, the `goal` field is already filled as the screenshot below:
<img width="1164" alt="screen shot 2016-10-28 at 13 14 59" src="https://cloud.githubusercontent.com/assets/5435389/19811832/e104d54e-9d11-11e6-9da9-e1fbce26cf48.png">

So, the payload that i'll send to **create** endpoit is:
```
{
  mobilization_id: (int),
  global: (bool),
  name: (string),
  goal: (string)
}
```
